Repository lugnitdgp/Hack-Day, pull requests merged in 2020-10, with the labels that each got.

#309 Added profile AStar
  data.json
Labels: Changes requested

#331 Added a repo card Photoblog
  Hack-Day-2020/repos.json
Labels: hacktoberfest-accepted

#328 Add profile nukumalik
  data.json
Labels: hacktoberfest-accepted

#332 Add profile raj0512gaurav
  data.json
Labels: hacktoberfest-accepted

#329 Changes made to the data.json file
  data.json
Labels: hacktoberfest-accepted

#321 Adding my profile, avatar and a short msg!
  data.json
Labels: Changes requested

#375 Added profile RishavHimmatramka
  data.json
Labels: hacktoberfest-accepted

#379 Added profile alannunes
  data.json
Labels: hacktoberfest-accepted

#336 Added a Vue-Project: "Buy-me-a-beer-Button"
  repos.json
Labels: Changes requested

#367 Added profile sujoy-coder
  data.json
Labels: Changes requested

#378 Added profile norabalogh
  data.json
Labels: Changes requested, Under review

#393 Update data.json
  data.json
Labels: hacktoberfest-accepted
